version: "3.8"
services:
  # # Mongo DB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=herox
      - MONGO_INITDB_ROOT_PASSWORD=123@123
    restart: unless-stopped
    networks:
      - herox-network

  # N8n
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    depends_on:
      - mongodb
      - app
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://herox:123@123@mongodb:27017
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_local_file:/files
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    networks:
      - herox-network

  # Node.js App
  app:
    build:
      context: .
      dockerfile: .dh-build/Dockerfile
    container_name: herox-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - C:/Users/Hero/Documents/Coding/X/trafix kaito - n8n/assets:/app/assets
    networks:
      - herox-network

  herox-ui:
    build:
      context: .
      dockerfile: .dh-build/Dockerfile.UI
    container_name: herox-ui
    ports:
      - "4454:8080"
    depends_on:
      - app
    env_file:
      - /ui/herox-ui/.env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://app:3000

    restart: unless-stopped
    networks:
      - herox-network

  # Ngrok
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command:
      - "http"
      - "herox-ui:4454" # Kết nối vào service tên là "herox-server"
      - --domain=${NGROK_STATIC_DOMAIN}
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - herox-ui
    restart: unless-stopped
    networks:
      - herox-network

volumes:
  mongodb_data:
  n8n_data:
  n8n_local_file:

networks:
  herox-network:
    driver: bridge
