version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=herox
      - MONGO_INITDB_ROOT_PASSWORD=123@123
    volumes:
      - mongodb_data:/data/db
    networks:
      - herox-network

  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass heroxredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - herox-network

  app:
    image: buikiet011/herox-server:latest
    container_name: herox-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - LOG_DEBUG=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=heroxredis
      - MONGO_URI=mongodb://herox:123@123@mongodb:27017/herox?authSource=admin
    volumes:
      - app_assets:/app/assets
    networks:
      - herox-network

  herox-ui:
    image: buikiet011/herox-ui:latest
    container_name: herox-ui
    restart: unless-stopped
    ports:
      - "4454:8080"
    depends_on:
      - app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://herox-server:3000
    networks:
      - herox-network

volumes:
  mongodb_data:
  redis_data:
  app_assets:

networks:
  herox-network:
    driver: bridge
